t = str(input('Digite algo: '))
print(f'O tipo primitivo desse valor é {type(t)}')
print(f'Só tem espaços? {t.isspace()}')
print(f'É um número? {t.isnumeric()}')
print(f'É alfabético? {t.isalpha()}')
print(f'É alfanumérico? {t.isalnum()}')
print(f'Está em maiúsculas? {t.isupper()}')
print(f'Está em minúsculas? {t.islower()}')
print(f'Está capitalizado? {t.istitle()}')
